export const SET_TRIPS_POPULAR = "SET_TRIPS_POPULAR";
export const SET_SCHEDULE = "SET_SCHEDULE";
export const SET_SEARCH_TRIPS = "SET_SEARCH_TRIPS";

export const GET_SEARCH_TRIP_SAGA = "GET_SEARCH_TRIP_SAGA";
export const GET_TO_SCHEDULE_SAGA = "GET_TO_SCHEDULE_SAGA";
export const GET_SCHEDULE_SAGA = "GET_SCHEDULE_SAGA";
export const GET_TRIPS_POPULAR_SAT_GA = "GET_TRIPS_POPULAR_SAT_GA";
export const GET_FIND_BUS_SAGA = "GET_FIND_BUS_SAGA";