export const translationsEn = {
    home: "HOME",
    schedule: "SCHEDULE",
    news: "NEWS",
    recruitment: "RECRUITMENT",
    contact: "CONTACT",
    receipt: "RECEIPT",
    aboutus: "ABOUT US",
    login: "Login",
    oneWay : "One way",
    roundTrip : "Round trip",
    origin : "Origin",
    dest : 'Destination',
    findBus : "Find the bus",
    departure : "Departure day",
    return : "Return day",
    popularSchedule : "Popular Schedule",
    quality : "QUALITY IS HONOR",
    destinations : "Popular destinations",
    tourist : 'Suggesting favorite tourist destinations of the year',
    chooseOrigin : "Choose origin",
    chooseDestination : "Choose Destination"
};

export const translationsVi = {
    home: "TRANG CHỦ",
    schedule: "LỊCH TRÌNH",
    news: "TIN TỨC",
    recruitment: "TUYỂN DỤNG",
    contact: "LIÊN HỆ",
    receipt: "HÓA ĐƠN",
    aboutus: "VỀ CHÚNG TÔI",
    login: "Đăng nhập",
    oneWay: "Một chiều",
    roundTrip: "Khứ hồi",
    origin: "Điểm đi",
    dest: "Điểm đến",
    findBus : "Tìm chuyến xe",
    departure : "Ngày đi",
    return : "Ngày về",
    popularSchedule : "Tuyến phổ biến",
    quality : "Chất lượng là danh dự",
    destinations : "điểm đến phổ biến",
    tourist : 'Gợi ý những điểm du lịch được ưa thích trong năm',
    chooseOrigin : "Chọn điểm đi",
    chooseDestination : "Chọn điểm đến"

};
